# Generated by Django 3.2.4 on 2022-08-20 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255, unique=True)),
                ('quotation_no', models.CharField(max_length=255)),
                ('user_id', models.PositiveBigIntegerField()),
                ('customer_id', models.PositiveBigIntegerField()),
                ('customer_first_name', models.CharField(max_length=255)),
                ('customer_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_transfer', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mobile_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('issued_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255)),
                ('product_id', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=191, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picked', models.BooleanField(default=False)),
                ('refund_status', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_total_after_refund', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_refunded', models.DateTimeField(blank=True, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoices')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
