# Generated by Django 3.2.4 on 2022-08-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitems',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='picked',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='refund_quantity',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='refunded_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitems',
            name='sub_total_after_refund',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='business_name',
        ),
    ]
