# Generated by Django 3.2.4 on 2022-08-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=191)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=191, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=191, null=True)),
                ("address", models.CharField(blank=True, max_length=191, null=True)),
                (
                    "customer_code",
                    models.CharField(blank=True, max_length=191, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
