# Generated by Django 3.2.4 on 2022-08-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(default="CUS1", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="cust@gmail.com", max_length=191),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="Doe", max_length=191),
            preserve_default=False,
        ),
    ]
